### ISSUE TITLE
修正必要箇所

### ISSUE THREAD

**Issue by minidora3** [minidora3/original_app#20]
## What
修正必要箇所
- トップページにインデックスページへのリンクはる
- Talkroom一覧が正しく表示されていない

**Comment by ArakawaShintaro** [comment]
期日
- 修正箇所 7/10
- デザイン7/14

**Comment by minidora3** [comment]
お疲れ様です。
修正についてアップデートします。
Talkroom一覧が正しく表示されない件について、
原因は判明しましたが、解決に至っていません。
事象としては、対象記事（Advert）が削除（論理削除）された場合、
それにひもずくTalkroomが見れない、でした。
Talkroomを探しに行く際に、ログインしているユーザが投稿募集があるかで判断し、
募集記事があればその記事idにひもずくTalkroomを一覧として表示、
なければ自分のtalkroomのuser_idが自分と同じもの）としており、
①投稿主の場合、投稿記事が論理削除で検索対象にならない
②投稿主以外、自分のidがひもずくTalkroomが、参照できない（論理削除された）記事のidをもっている


```
def index
    if current_user.advert.present?
      @talkrooms = Talkroom.where(advert_id: current_user.advert.id)
    else
      @talkrooms = Talkroom.where(user_id: current_user)
    end
end
```

paranoiaのgitで、論理削除されたレコードの取得方法も記載されているので、
以下のように追加してみたのですが、うまく行かず・・・な状態です。

```
@advert = Advert.where(advert_id: current_user).with_deleted
```
